source "https://rubygems.org"

ruby "3.2.2"

gem "rails", "~> 8.0.0"

gem "bcrypt", "~> 3.1.7"
gem "bootsnap", require: false
gem "image_processing", "~> 1.2"
gem "importmap-rails"
gem "jbuilder"
gem "propshaft"
gem "puma", ">= 5.0"
gem "sqlite3", "~> 2.1"
gem "stimulus-rails"
gem "turbo-rails"
gem "tzinfo-data", platforms: %i[windows jruby]
gem "lucide-rails"
gem "sidekiq"

group :development do
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
  gem "web-console"
end
